<a href="https://colab.research.google.com/github/aytekin827/AIB_03_SprintChallenge/blob/main/PyTorch%EB%A1%9C_%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94_%EB%94%A5_%EB%9F%AC%EB%8B%9D_%EC%9E%85%EB%AC%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 03-05 클래스로 파이토치 모델 구현하기

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)

단순 선형회귀모델 구현

In [24]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self): #
        super().__init__()
        self.linear = nn.Linear(1, 1) # 단순 선형 회귀이므로 input_dim=1, output_dim=1.

    def forward(self, x):
        return self.linear(x)

simple_linear_model = LinearRegressionModel()

In [25]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [26]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(simple_linear_model.parameters(), lr=0.01)

In [27]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = simple_linear_model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 18.474602
Epoch  100/2000 Cost: 0.136136
Epoch  200/2000 Cost: 0.084124
Epoch  300/2000 Cost: 0.051984
Epoch  400/2000 Cost: 0.032123
Epoch  500/2000 Cost: 0.019850
Epoch  600/2000 Cost: 0.012266
Epoch  700/2000 Cost: 0.007580
Epoch  800/2000 Cost: 0.004684
Epoch  900/2000 Cost: 0.002894
Epoch 1000/2000 Cost: 0.001788
Epoch 1100/2000 Cost: 0.001105
Epoch 1200/2000 Cost: 0.000683
Epoch 1300/2000 Cost: 0.000422
Epoch 1400/2000 Cost: 0.000261
Epoch 1500/2000 Cost: 0.000161
Epoch 1600/2000 Cost: 0.000100
Epoch 1700/2000 Cost: 0.000062
Epoch 1800/2000 Cost: 0.000038
Epoch 1900/2000 Cost: 0.000023
Epoch 2000/2000 Cost: 0.000015


In [28]:
test_tensor = torch.FloatTensor([[10]])
simple_linear_model(test_tensor)

tensor([[19.9659]], grad_fn=<AddmmBackward0>)

In [40]:
for param in simple_linear_model.parameters():
    print(param)

Parameter containing:
tensor([[1.9956]], requires_grad=True)
Parameter containing:
tensor([0.0100], requires_grad=True)


다중 선형 회귀 모델

In [29]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

multi_linear_model = MultivariateLinearRegressionModel()

In [30]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [31]:
optimizer = torch.optim.SGD(multi_linear_model.parameters(), lr=1e-5)

In [32]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = multi_linear_model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 24821.373047
Epoch  100/2000 Cost: 0.849148
Epoch  200/2000 Cost: 0.825597
Epoch  300/2000 Cost: 0.803225
Epoch  400/2000 Cost: 0.781968
Epoch  500/2000 Cost: 0.761775
Epoch  600/2000 Cost: 0.742599
Epoch  700/2000 Cost: 0.724357
Epoch  800/2000 Cost: 0.707025
Epoch  900/2000 Cost: 0.690548
Epoch 1000/2000 Cost: 0.674883
Epoch 1100/2000 Cost: 0.659985
Epoch 1200/2000 Cost: 0.645810
Epoch 1300/2000 Cost: 0.632342
Epoch 1400/2000 Cost: 0.619514
Epoch 1500/2000 Cost: 0.607307
Epoch 1600/2000 Cost: 0.595680
Epoch 1700/2000 Cost: 0.584620
Epoch 1800/2000 Cost: 0.574083
Epoch 1900/2000 Cost: 0.564048
Epoch 2000/2000 Cost: 0.554477


In [33]:
test_tensor = torch.FloatTensor([[73, 80, 75]])
multi_linear_model(test_tensor)

tensor([[151.6526]], grad_fn=<AddmmBackward0>)

In [41]:
for param in multi_linear_model.parameters():
    print(param)

Parameter containing:
tensor([[0.7497, 0.4868, 0.7725]], requires_grad=True)
Parameter containing:
tensor([0.0386], requires_grad=True)


# 03-06 미니 배치와 데이터 로드(Mini Batch and Data Load)

https://wikidocs.net/55580

데이터셋, 데이터로더 사용법

**Dataset정의** => **DataLoader에 전달**

In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [43]:
from torch.utils.data import TensorDataset # 텐서 데이터셋
from torch.utils.data import DataLoader # 데이터 로더

In [44]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [45]:
dataset = TensorDataset(x_train, y_train)

In [5]:
# 데이터로더는 Dataset과 batch_size를 인자로 받
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [49]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        print(f'{batch_idx=}')
        print(samples)
        x_train, y_train = samples
        # H(x) 계산
        prediction = multi_linear_model(x_train)

        # cost 계산
        cost = F.mse_loss(prediction, y_train)

        # cost로 H(x) 계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, batch_idx+1, len(dataloader),
            cost.item()
            ))
    print()


batch_idx=0
[tensor([[89., 91., 90.],
        [73., 66., 70.]]), tensor([[180.],
        [142.]])]
Epoch    0/20 Batch 1/3 Cost: 0.675881
batch_idx=1
[tensor([[ 96.,  98., 100.],
        [ 73.,  80.,  75.]]), tensor([[196.],
        [152.]])]
Epoch    0/20 Batch 2/3 Cost: 0.737256
batch_idx=2
[tensor([[93., 88., 93.]]), tensor([[185.]])]
Epoch    0/20 Batch 3/3 Cost: 0.352014

batch_idx=0
[tensor([[ 96.,  98., 100.],
        [ 89.,  91.,  90.]]), tensor([[196.],
        [180.]])]
Epoch    1/20 Batch 1/3 Cost: 1.070808
batch_idx=1
[tensor([[93., 88., 93.],
        [73., 66., 70.]]), tensor([[185.],
        [142.]])]
Epoch    1/20 Batch 2/3 Cost: 1.078855
batch_idx=2
[tensor([[73., 80., 75.]]), tensor([[152.]])]
Epoch    1/20 Batch 3/3 Cost: 0.064662

batch_idx=0
[tensor([[ 96.,  98., 100.],
        [ 73.,  66.,  70.]]), tensor([[196.],
        [142.]])]
Epoch    2/20 Batch 1/3 Cost: 1.080650
batch_idx=1
[tensor([[93., 88., 93.],
        [89., 91., 90.]]), tensor([[185.],
        [180.]]

# 03-07 커스텀 데이터셋(Custom Dataset)